on:
    push:
      branches:
        - main
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: "22"
        - name: Install Dependencies
          run: npm install
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.11"
        - name: Setup SAM
          uses: aws-actions/setup-sam@v2
          with:
            use-installer: true
        - uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        # for testing by jest mock
        - run: npm run unit
        # Build inside Docker containers
        - run: sam build 
        # Prevent prompts and failure when the stack is unchanged
        - run: |
            sam deploy --stack-name ${{secrets.stackName}}
            